spring:
  datasource:
    # HSQL can run in memory (temporary) or file-based (persistent) mode
    # For in-memory database:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    # For file-based database:
    # url: jdbc:hsqldb:file:./data/testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

  jpa:
    hibernate:
      # In development, you might want to use 'create-drop' to recreate the schema each time
      # For production, 'update' is more appropriate
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        format_sql: true
    show-sql: true
    # Defers datasource initialization until after EntityManagerFactory is created
    defer-datasource-initialization: true

  # Enables data.sql script execution
  sql:
    init:
      mode: always